# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acbc11cf9e8f33d38f22ede344fad27fe58faea70c3dc963cd69ae7db5d5f3fd31eaf9e63e109bd83b4b4c2706802be29aa81ef38785d9870dcbc258a8094569

test:
  secret_key_base: 7c673b36bced2b8600f9988743a6f49311e3776a60a43f96a5a6b5b82a30149159458bda0b1f61b4d90e9cfa712322237cb9708d12e17ec82788b54fee42e017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
